//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCG.EPi.Enterprise.Migration.Toolset.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VCG.EPi.Enterprise.Migration.Toolset.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About (not implemented).
        /// </summary>
        public static string ApplicationAbout {
            get {
                return ResourceManager.GetString("ApplicationAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPiServer 5 &amp; 6 data upgrade tool (beta).
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string ButtonRestart {
            get {
                return ResourceManager.GetString("ButtonRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes generated.
        /// </summary>
        public static string ClassesGenerated {
            get {
                return ResourceManager.GetString("ClassesGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string ColumnAlias {
            get {
                return ResourceManager.GetString("ColumnAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block?.
        /// </summary>
        public static string ColumnBlockQuestion {
            get {
                return ResourceManager.GetString("ColumnBlockQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ColumnId {
            get {
                return ResourceManager.GetString("ColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target name.
        /// </summary>
        public static string ColumnTargetName {
            get {
                return ResourceManager.GetString("ColumnTargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration projects (.mgproj)|*.mgproj|All files (*.*)|*.*.
        /// </summary>
        public static string DocumentFilters {
            get {
                return ResourceManager.GetString("DocumentFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document loaded successfully.
        /// </summary>
        public static string DocumentLoaded {
            get {
                return ResourceManager.GetString("DocumentLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document loading {0:0.0} %.
        /// </summary>
        public static string DocumentLoading {
            get {
                return ResourceManager.GetString("DocumentLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening document....
        /// </summary>
        public static string DocumentOpening {
            get {
                return ResourceManager.GetString("DocumentOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document saved.
        /// </summary>
        public static string DocumentSaved {
            get {
                return ResourceManager.GetString("DocumentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnnamedMigrationProject.
        /// </summary>
        public static string DocumentSaveFileName {
            get {
                return ResourceManager.GetString("DocumentSaveFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration projects (.mgproj)|*.mgproj.
        /// </summary>
        public static string DocumentSaveFilter {
            get {
                return ResourceManager.GetString("DocumentSaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string ErrorFormat {
            get {
                return ResourceManager.GetString("ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export aborted, not enough data.
        /// </summary>
        public static string ExportAbortedNoData {
            get {
                return ResourceManager.GetString("ExportAbortedNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export aborted, no matching properties.
        /// </summary>
        public static string ExportAbortedNoMatches {
            get {
                return ResourceManager.GetString("ExportAbortedNoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export aborted by user.
        /// </summary>
        public static string ExportAbortedUser {
            get {
                return ResourceManager.GetString("ExportAbortedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        public static string ExportProgress {
            get {
                return ResourceManager.GetString("ExportProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnnamedEPiServerExport.
        /// </summary>
        public static string ExportSaveFileName {
            get {
                return ResourceManager.GetString("ExportSaveFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPiServer data (.episerverdata)|*.episerverdata.
        /// </summary>
        public static string ExportSaveFilter {
            get {
                return ResourceManager.GetString("ExportSaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder for export.
        /// </summary>
        public static string ExportSelectFolder {
            get {
                return ResourceManager.GetString("ExportSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File read successfully.
        /// </summary>
        public static string FileImported {
            get {
                return ResourceManager.GetString("FileImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter default namespace.
        /// </summary>
        public static string HeadingBaseNamespace {
            get {
                return ResourceManager.GetString("HeadingBaseNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map to target type.
        /// </summary>
        public static string HeadingMapToTarget {
            get {
                return ResourceManager.GetString("HeadingMapToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching properties:.
        /// </summary>
        public static string HeadingMatchingProperties {
            get {
                return ResourceManager.GetString("HeadingMatchingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target EPiServer version.
        /// </summary>
        public static string HeadingOptionsEPiServerVersion {
            get {
                return ResourceManager.GetString("HeadingOptionsEPiServerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included page type attributes.
        /// </summary>
        public static string HeadingOptionsPageTypeAttributes {
            get {
                return ResourceManager.GetString("HeadingOptionsPageTypeAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included property attributes.
        /// </summary>
        public static string HeadingOptionsPropertyAttributes {
            get {
                return ResourceManager.GetString("HeadingOptionsPropertyAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization options.
        /// </summary>
        public static string HeadingPreferencesLocalization {
            get {
                return ResourceManager.GetString("HeadingPreferencesLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file contents (.episerverdata).
        /// </summary>
        public static string HeadingSourceFileContents {
            get {
                return ResourceManager.GetString("HeadingSourceFileContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPiServer data (.episerverdata)|*.episerverdata.
        /// </summary>
        public static string ImportFilters {
            get {
                return ResourceManager.GetString("ImportFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select source file.
        /// </summary>
        public static string ImportSourceTitle {
            get {
                return ResourceManager.GetString("ImportSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file for target mappings.
        /// </summary>
        public static string ImportTargetTitle {
            get {
                return ResourceManager.GetString("ImportTargetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter skipped {0}, conflicting file name.
        /// </summary>
        public static string LogClassConflictFormat {
            get {
                return ResourceManager.GetString("LogClassConflictFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating class &apos;{0}&apos;.
        /// </summary>
        public static string LogGeneratingClassFormat {
            get {
                return ResourceManager.GetString("LogGeneratingClassFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _EDIT.
        /// </summary>
        public static string MenuCategoryEdit {
            get {
                return ResourceManager.GetString("MenuCategoryEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _EXPORT.
        /// </summary>
        public static string MenuCategoryExport {
            get {
                return ResourceManager.GetString("MenuCategoryExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _FILE.
        /// </summary>
        public static string MenuCategoryFile {
            get {
                return ResourceManager.GetString("MenuCategoryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _IMPORT.
        /// </summary>
        public static string MenuCategoryImport {
            get {
                return ResourceManager.GetString("MenuCategoryImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export EPiServer 7 class files....
        /// </summary>
        public static string MenuExportClasses {
            get {
                return ResourceManager.GetString("MenuExportClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export EPiServer 7 import file....
        /// </summary>
        public static string MenuExportImportFile {
            get {
                return ResourceManager.GetString("MenuExportImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import EPiServer 5/6 data....
        /// </summary>
        public static string MenuImportSource {
            get {
                return ResourceManager.GetString("MenuImportSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import EPiServer 7 target data....
        /// </summary>
        public static string MenuImportTarget {
            get {
                return ResourceManager.GetString("MenuImportTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string MenuPreferences {
            get {
                return ResourceManager.GetString("MenuPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 7.1.
        /// </summary>
        public static string OptionsEPiVersion7_1 {
            get {
                return ResourceManager.GetString("OptionsEPiVersion7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 7.5.
        /// </summary>
        public static string OptionsEPiVersion7_5 {
            get {
                return ResourceManager.GetString("OptionsEPiVersion7_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will not take effect before application is restarted.
        /// </summary>
        public static string PreferenceRestartNotice {
            get {
                return ResourceManager.GetString("PreferenceRestartNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface language.
        /// </summary>
        public static string PreferenceUILanguage {
            get {
                return ResourceManager.GetString("PreferenceUILanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade completed successfully.
        /// </summary>
        public static string UpgradeComplete {
            get {
                return ResourceManager.GetString("UpgradeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading {0} %.
        /// </summary>
        public static string UpgradeProgress {
            get {
                return ResourceManager.GetString("UpgradeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class export options.
        /// </summary>
        public static string WindowTitleExportOptions {
            get {
                return ResourceManager.GetString("WindowTitleExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation status.
        /// </summary>
        public static string WindowTitleOperationStatus {
            get {
                return ResourceManager.GetString("WindowTitleOperationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string WindowTitlePreferences {
            get {
                return ResourceManager.GetString("WindowTitlePreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remap properties (alias).
        /// </summary>
        public static string WindowTitleRemap {
            get {
                return ResourceManager.GetString("WindowTitleRemap", resourceCulture);
            }
        }
    }
}
